import { Link } from 'react-router-dom';

/* eslint-disable react/no-unescaped-entities */
/** Conditions d’utilisation — version française de TermsDoc.tsx. Les deux doivent rester alignées. */
export default function TermsDocFr() {
  return (
    <>
    <p><strong>CONDITIONS D’UTILISATION DE Plotbreak</strong></p>

    <p>Dernière mise à jour : 2026-09-10{"\n"}Les présentes Conditions s’appliquent à tous les utilisateurs à compter du 2026-09-10. Pour les nouveaux utilisateurs qui s’inscrivent après la date de dernière mise à jour, elles s’appliquent dès l’inscription et l’acceptation.</p>

    <p>Les présentes Conditions d’utilisation (les <strong>« Conditions »</strong>) régissent votre accès à notre site Web situé à l’adresse <a href="https://plotbreak.com">https://plotbreak.com</a> (le <strong>« Site Web »</strong>) et votre utilisation de celui-ci, ainsi que l’utilisation de notre application mobile Plotbreak (l’<strong>« Application »</strong>). Elles régissent également votre accès aux services et au contenu offerts par l’entremise du Site Web et de l’Application et leur utilisation (collectivement avec le Site Web et l’Application, les <strong>« Services »</strong>). Les présentes Conditions constituent une entente juridiquement contraignante entre tous les visiteurs, utilisateurs et autres personnes qui accèdent aux Services ou les utilisent (<strong>« vous »</strong>, <strong>« votre »</strong>) et Plotbreak (collectivement la <strong>« Société »</strong>, <strong>« nous »</strong>, <strong>« notre »</strong> ou <strong>« nos »</strong>). Si vous concluez les présentes Conditions au nom d’une société, d’une organisation ou d’une entité semblable, vous acceptez les Conditions pour cette entité et vous déclarez avoir le pouvoir de la lier.</p>

    <p>En accédant aux Services, en les utilisant ou en interagissant avec eux, vous indiquez avoir lu et compris les présentes Conditions et accepter d’y être lié. Si vous n’acceptez pas les présentes Conditions, vous devez cesser d’accéder aux Services ou de les utiliser. Votre utilisation des Services peut être assujettie à des conditions juridiques supplémentaires, à des conditions propres à certains services, à des lignes directrices et à des politiques (les <strong>« Conditions supplémentaires »</strong>). Le cas échéant, elles vous seront présentées au fur et à mesure de votre utilisation des Services et sont intégrées aux présentes par renvoi. En cas de conflit entre les présentes Conditions et les Conditions supplémentaires, ces dernières prévalent.</p>

    <p><strong>REMARQUE IMPORTANTE : VEUILLEZ LIRE ATTENTIVEMENT LES PRÉSENTES CONDITIONS, CAR ELLES PEUVENT AVOIR UNE INCIDENCE SUR VOS DROITS EN CAS DE LITIGE ENTRE NOUS. CONSULTEZ EN PARTICULIER LA SECTION INTITULÉE « <a href="#disputes">RÈGLEMENT DES DIFFÉRENDS; CONVENTION D’ARBITRAGE; RENONCIATION AUX RECOURS COLLECTIFS ET AU PROCÈS DEVANT JURY</a> », QUI EXIGE QUE LES DIFFÉRENDS SOIENT RÉGLÉS PAR ARBITRAGE INDIVIDUEL EXÉCUTOIRE PLUTÔT QUE DEVANT LES TRIBUNAUX ET QUI COMPORTE UNE RENONCIATION À VOTRE DROIT DE PARTICIPER À UN RECOURS COLLECTIF.</strong></p>

    <p>À l’exception de l’article 13, qui prévoit un arbitrage exécutoire et une renonciation aux recours collectifs, nous nous réservons le droit de modifier les présentes Conditions à tout moment. En cas de modification importante, nous vous en aviserons en publiant les Conditions mises à jour dans l’Application ou sur le Site Web, en actualisant la date de « Dernière mise à jour » et, lorsque la loi l’exige, par un avis supplémentaire. Votre utilisation continue des Services après l’entrée en vigueur des modifications constitue votre acceptation des Conditions modifiées.</p>

    <ol className="heading" start={1}><li><strong>ADMISSIBILITÉ ET COMPTE D’UTILISATEUR.</strong></li></ol>

    <p><strong>a. Utilisation et admissibilité.</strong> En accédant aux Services ou en les utilisant, vous acceptez d’être lié par les présentes Conditions et par notre <Link to="/fr/privacy">Politique de confidentialité</Link> et de vous y conformer. Vous devez avoir au moins 13 ans pour utiliser les Services. Si vous avez entre 13 ans et l’âge de la majorité dans votre juridiction, vous ne pouvez utiliser les Services qu’avec la permission d’un parent ou d’un tuteur légal qui accepte d’être lié par les présentes Conditions en votre nom. Les Services contiennent de la violence fantastique, des thèmes matures et des relations qui peuvent échouer; l’Application est classée en conséquence sur l’App Store.</p>

    <p>Vous ne pouvez utiliser les Services que si vous êtes en mesure de conclure un contrat contraignant avec la Société (en votre nom ou au nom de l’entité que vous représentez), et uniquement dans le respect des présentes Conditions et de toutes les lois applicables. Vous ne pouvez pas utiliser les Services si vous avez déjà été suspendu ou exclu des Services.</p>

    <p><strong>b. Compte d’utilisateur et inscription.</strong> Pour utiliser les Services, vous pouvez jouer en tant qu’invité ou créer un compte au moyen de Se connecter avec Apple ou d’un code de connexion envoyé par courriel (un <strong>« Compte d’utilisateur »</strong>). Un compte invité est rattaché à votre appareil; si vous supprimez l’Application ou perdez l’appareil sans avoir converti le compte en compte inscrit, vos histoires et votre solde de Crédits pourraient être irrécupérables. Vous acceptez de fournir des renseignements exacts, y compris votre tranche d’âge, et de les tenir à jour. Vous êtes responsable de toute activité effectuée sous votre Compte d’utilisateur et de la confidentialité de vos codes de connexion. Vous devez nous aviser immédiatement à <a href="mailto:hi@cielpm.ai">hi@cielpm.ai</a> de toute utilisation non autorisée de votre Compte d’utilisateur.</p>

    <p>Nous nous réservons le droit de fermer, de suspendre ou de limiter l’accès à votre Compte d’utilisateur et/ou aux Services si nous déterminons, à notre entière discrétion, que vous avez enfreint les présentes Conditions, faussement déclaré votre âge ou utilisé les Services d’une manière susceptible de nous nuire ou de nuire à d’autres utilisateurs.</p>

    <ol className="heading" start={2}><li><strong>LES SERVICES.</strong></li></ol>

    <p><strong>a. Description des Services.</strong> Plotbreak est un jeu de rôle interactif. Vous saisissez librement des actions et des dialogues; un moteur de règles déterministe détermine ce qui se passe; et des outils d’intelligence artificielle interprètent votre saisie et décrivent le résultat en texte et en images. Les Services comprennent un catalogue d’histoires écrites par la Société, une économie fondée sur des Crédits pour jouer des tours, et des fonctionnalités comme les bifurcations, la reformulation, la correction de canon, l’épinglage et le partage. Nous pouvons ajouter, modifier ou retirer des histoires et des fonctionnalités à tout moment.</p>

    <p><strong>b. Contenu d’utilisateur.</strong> En utilisant les Services, vous pouvez soumettre du texte, des actions, des dialogues, des descriptions, des commentaires, des signalements et d’autres éléments (le <strong>« Contenu d’utilisateur »</strong>). Vous êtes seul responsable de votre Contenu d’utilisateur. Vous déclarez et garantissez que vous détenez les droits nécessaires pour le soumettre et qu’il ne contrevient ni aux présentes Conditions, ni aux lois applicables, ni aux droits de tiers. La Société n’endosse aucun Contenu d’utilisateur et n’en est pas responsable.</p>

    <p>Nous nous réservons le droit de filtrer le Contenu d’utilisateur au moyen d’une modération automatisée avant qu’il serve à jouer un tour, de refuser de traiter tout Contenu d’utilisateur, et de retirer ou de refuser tout Contenu d’utilisateur pour quelque raison que ce soit, sans préavis. La modération automatisée peut être imparfaite; vous pouvez nous demander de faire réviser une décision de modération.</p>

    <p><strong>c. Contenu généré.</strong> Le texte, les images et l’état de jeu produits par les Services en réponse à votre Contenu d’utilisateur (le <strong>« Contenu généré »</strong>) sont créés par notre moteur de règles et nos Outils d’IA (définis ci-dessous). Le Contenu généré est de la fiction. Il peut dépeindre des conflits, des pertes, la mort, des trahisons et d’autres thèmes matures dans le cadre de l’histoire. Il ne constitue en aucun cas un conseil.</p>

    <p><strong>d. Utilisation et restrictions.</strong> Vous n’utiliserez les Services qu’à des fins de divertissement personnel et non commercial, conformément aux présentes Conditions. Vous acceptez de ne pas, et de ne permettre à personne de :</p>

    <ul>
      <li>soumettre du Contenu d’utilisateur illégal, qui sexualise des mineurs, qui constitue du harcèlement, des menaces ou des propos haineux visant des personnes réelles, ou qui fait la promotion de l’automutilation, du terrorisme ou de la violence dans le monde réel;</li>
      <li>utiliser les Services pour générer du contenu qui porte atteinte aux droits de propriété intellectuelle, à la vie privée ou au droit à l’image de quiconque;</li>
      <li>tenter d’extraire, de rétroconcevoir, de moissonner ou de perturber le moteur de règles, les instructions, les modèles, les API ou l’infrastructure sous-jacents aux Services, ou contourner toute limite de débit, vérification de Crédits, modération ou mesure de sécurité;</li>
      <li>utiliser des moyens automatisés (robots, scripts ou agents) pour jouer des tours ou accéder autrement aux Services;</li>
      <li>acheter, vendre, échanger ou transférer des Comptes d’utilisateur ou des Crédits, ou utiliser un mode de paiement que vous n’êtes pas autorisé à utiliser;</li>
      <li>usurper l’identité d’une personne ou d’une entité, ou faire une fausse déclaration quant à votre âge ou à votre affiliation avec une personne ou une entité;</li>
      <li>utiliser les Services pour développer un produit concurrent ou pour entraîner un modèle d’apprentissage automatique; ou</li>
      <li>utiliser les Services d’une manière qui contrevient aux lois applicables ou aux présentes Conditions.</li>
    </ul>

    <ol className="heading" start={3}><li><strong>SERVICES PAYANTS ET CRÉDITS.</strong></li></ol>

    <p><strong>a. Crédits.</strong> Jouer un tour dans les Services consomme des <strong>« Crédits »</strong>. Les Crédits sont la monnaie interne des Services. Ils ne remplacent pas une monnaie réelle, n’ont aucune valeur monétaire, ne sont pas échangeables contre de l’argent, ne peuvent être transférés à une autre personne ou à un autre compte, et constituent une licence limitée d’utilisation des fonctionnalités correspondantes des Services. Nous pouvons accorder des Crédits gratuitement (par exemple, un solde de départ et une allocation quotidienne) et nous pouvons modifier à tout moment le montant accordé, le coût d’un tour ou d’un palier de qualité, et les fonctionnalités offertes à chaque palier.</p>

    <p><strong>b. Lots de Crédits; paiement.</strong> Des Crédits supplémentaires peuvent être achetés dans l’Application sous forme d’achats intégrés uniques et consommables (les <strong>« Lots de Crédits »</strong>). Tous les achats sont traités par Apple (App Store) ou Google (Google Play) (chacun, un <strong>« Processeur de paiement »</strong>) selon leurs propres conditions et politiques de paiement. Nous ne recevons ni ne conservons les données de votre carte de paiement. Les prix sont affichés dans l’Application avant que vous confirmiez un achat et peuvent varier selon la région. Les Crédits achetés par l’entremise d’un Processeur de paiement ne sont ajoutés à votre Compte d’utilisateur qu’une fois la transaction vérifiée par nos serveurs auprès du Processeur de paiement; si un achat est complété sans être crédité, il le sera automatiquement au prochain lancement de l’Application, ou vous pouvez utiliser Restaurer les achats ou nous joindre.</p>

    <p><strong>c. Aucun abonnement; aucun rechargement automatique.</strong> Pour l’instant, les Services n’offrent ni abonnement ni achat récurrent automatique. Si nous en introduisons à l’avenir, les conditions, le prix et le mode d’annulation applicables vous seront communiqués avant votre adhésion.</p>

    <p><strong>d. Remboursements.</strong> Tous les achats de Lots de Crédits sont définitifs et non remboursables, sauf lorsque la loi applicable ou les politiques de remboursement du Processeur de paiement l’exigent. Les demandes de remboursement pour les achats effectués sur l’App Store doivent être adressées à Apple, et celles pour les achats effectués sur Google Play, à Google; nous ne pouvons pas rembourser directement ces achats. Si un achat est remboursé ou fait l’objet d’une rétrofacturation, les Crédits correspondants seront déduits de votre solde, qui pourrait devenir négatif jusqu’à son remboursement.</p>

    <p><strong>e. Expiration des Crédits; fermeture du compte.</strong> Les Crédits achetés n’expirent pas tant que votre Compte d’utilisateur demeure actif. Les Crédits gratuits peuvent expirer ou être ajustés à tout moment. Tous les Crédits sont perdus, sans compensation, lorsque votre Compte d’utilisateur est fermé par vous ou résilié par nous pour violation des présentes Conditions, et les Crédits inutilisés d’un compte invité sont perdus si l’Application est supprimée avant l’inscription du compte.</p>

    <p><strong>f. Corrections.</strong> Les soldes et la consommation de Crédits sont établis d’après nos registres, qui font foi en l’absence d’erreur manifeste. Si vous croyez que votre solde est erroné, écrivez-nous à <a href="mailto:hi@cielpm.ai">hi@cielpm.ai</a> dans les 30 jours et nous ferons enquête. Nous pouvons corriger tout solde accordé ou consommé par erreur, y compris à la suite d’un bogue, d’une fraude ou d’un abus.</p>

    <p><strong>g. Règles égales.</strong> Le palier de qualité que vous choisissez n’a d’effet que sur la présentation d’un tour (longueur, profondeur de mémoire et génération ou non d’illustrations de scène). Il ne modifie ni le moteur de règles, ni la difficulté, ni les résultats aléatoires. Aucun achat ne confère d’avantage dans le jeu.</p>

    <ol className="heading" start={4}><li><strong>PROPRIÉTÉ INTELLECTUELLE.</strong></li></ol>

    <p><strong>a. Les Services.</strong> Entre vous et la Société, les Services, y compris sans limitation les histoires, les personnages, les mondes, les illustrations, les textes, le moteur de règles, les instructions, les logiciels, le design, les marques de commerce et tout autre contenu et matériel (autres que votre Contenu d’utilisateur), appartiennent à la Société ou à ses concédants de licence et sont protégés par les lois sur le droit d’auteur, les marques de commerce et d’autres lois. Sous réserve du respect des présentes Conditions, nous vous accordons une licence limitée, non exclusive, non transférable et révocable pour télécharger et utiliser l’Application sur un appareil de marque Apple ou Google que vous possédez ou contrôlez, et pour utiliser les Services à des fins de divertissement personnel et non commercial. Tous les droits non expressément accordés sont réservés.</p>

    <p><strong>b. Contenu d’utilisateur.</strong> Entre vous et la Société, vous êtes propriétaire de votre Contenu d’utilisateur. En le soumettant, vous accordez à la Société une licence mondiale, non exclusive, libre de redevances et pouvant faire l’objet de sous-licences pour héberger, stocker, reproduire, modifier, traiter et afficher votre Contenu d’utilisateur, et pour en créer du Contenu généré, aux fins de l’exploitation, de la fourniture, de la sécurisation, de l’évaluation et de l’amélioration des Services. Cette licence prend fin lorsque vous supprimez le Contenu d’utilisateur ou votre Compte d’utilisateur, sauf dans la mesure où le Contenu d’utilisateur a été partagé par vous, est conservé sous forme dépersonnalisée ou doit être conservé pour se conformer à la loi.</p>

    <p><strong>c. Contenu généré.</strong> Sous réserve des présentes Conditions et dans la mesure permise par la loi applicable, la Société vous cède les droits qu’elle pourrait détenir sur le texte du Contenu généré produit dans vos propres sessions d’histoire, et vous pouvez l’utiliser à des fins personnelles et non commerciales, y compris partager des captures d’écran et des cartes de partage. Le Contenu généré peut ne pas être unique; un résultat semblable ou identique peut être généré pour d’autres utilisateurs, et la Société ne garantit pas que le Contenu généré puisse être protégé par le droit d’auteur. Les histoires, les personnages, les mondes et les illustrations des Services demeurent la propriété de la Société, et rien dans le présent article ne transfère de droits sur ceux-ci.</p>

    <p><strong>d. Données d’utilisation et d’interaction.</strong> Nous pouvons recueillir et générer des données techniques, de diagnostic, d’utilisation, d’analyse et de performance concernant les Services; ces données nous appartiennent et nous pouvons les utiliser à toute fin licite, pourvu qu’elles ne vous identifient pas personnellement, sauf dans les cas prévus par notre Politique de confidentialité.</p>

    <p><strong>e. Commentaires.</strong> Si vous nous transmettez des commentaires, des suggestions ou des idées d’amélioration des Services (les <strong>« Commentaires »</strong>), vous nous accordez une licence perpétuelle, irrévocable, mondiale et libre de redevances pour les utiliser à toute fin, sans compensation ni attribution.</p>

    <ol className="heading" start={5}><li><strong>CONFIDENTIALITÉ.</strong></li></ol>

    <p>Pour en savoir plus sur nos pratiques en matière de données, y compris la collecte et l’utilisation de vos renseignements, veuillez lire notre <Link to="/fr/privacy">Politique de confidentialité</Link>, qui est intégrée aux présentes Conditions par renvoi.</p>

    <ol className="heading" start={6}><li><strong>FONCTIONNALITÉS D’INTELLIGENCE ARTIFICIELLE.</strong></li></ol>

    <p><strong>a. Fonctionnalités reposant sur l’IA.</strong> Certaines fonctionnalités des Services utilisent l’apprentissage automatique, l’intelligence artificielle générative et des technologies semblables (les <strong>« Technologies d’IA »</strong>) pour interpréter votre saisie, planifier et rédiger le texte de l’histoire, générer des images et modérer le contenu (collectivement, les <strong>« Outils d’IA »</strong>).</p>

    <p><strong>b. Entrées et sorties.</strong> Dans le cadre de votre utilisation des Outils d’IA, vous pouvez soumettre du texte et d’autres éléments (les <strong>« Entrées »</strong>), et les Outils d’IA génèrent du texte, des images ou d’autres résultats (les <strong>« Sorties »</strong>). Vous êtes responsable de vos Entrées. Vous reconnaissez que les Sorties sont générées automatiquement, qu’elles peuvent ressembler aux Sorties générées pour d’autres utilisateurs, et que c’est le moteur de règles, et non les Outils d’IA, qui détermine le résultat de toute action dans le jeu.</p>

    <p><strong>c. Outils d’IA de tiers.</strong> Les Outils d’IA comprennent des Technologies d’IA fournies par des tiers (les <strong>« Fournisseurs d’IA tiers »</strong>). Vos Entrées et l’état d’histoire connexe seront transmis aux Fournisseurs d’IA tiers pour traitement. Nous exigeons contractuellement des Fournisseurs d’IA tiers qu’ils traitent les Entrées et les Sorties uniquement en notre nom et qu’ils ne les utilisent pas pour entraîner leurs modèles.</p>

    <p><strong>d. Sorties de l’IA; absence de garantie.</strong> Les Sorties sont de la fiction générée par intelligence artificielle. Elles peuvent être inexactes, incomplètes, choquantes ou incohérentes avec des tours antérieurs, et ne reflètent pas nécessairement les opinions de la Société. Vous êtes seul responsable d’examiner et d’évaluer les Sorties avant de les partager ou de vous y fier. Les Sorties ne constituent pas des conseils médicaux, juridiques, financiers ou autres conseils professionnels.</p>

    <ol className="heading" start={7}><li><strong>EXCLUSIONS DE GARANTIE.</strong></li></ol>

    <p>DANS TOUTE LA MESURE PERMISE PAR LA LOI APPLICABLE, LES SERVICES SONT FOURNIS « TELS QUELS » ET « SELON LA DISPONIBILITÉ », SANS GARANTIE D’AUCUNE SORTE, EXPRESSE OU IMPLICITE, Y COMPRIS, SANS LIMITATION, LES GARANTIES IMPLICITES DE QUALITÉ MARCHANDE, D’ADAPTATION À UN USAGE PARTICULIER, DE TITRE ET D’ABSENCE DE CONTREFAÇON.</p>

    <p>SANS LIMITER CE QUI PRÉCÈDE, LA SOCIÉTÉ ET SES CONCÉDANTS DE LICENCE NE GARANTISSENT PAS QUE LES SERVICES RÉPONDRONT À VOS EXIGENCES; QU’ILS SERONT ININTERROMPUS, OPPORTUNS, SÉCURITAIRES OU EXEMPTS D’ERREURS; QUE LES SORTIES SERONT EXACTES OU FIABLES; NI QUE LES ERREURS DES SERVICES SERONT CORRIGÉES. LES HISTOIRES SAUVEGARDÉES PEUVENT ÊTRE PERDUES; LES BIFURCATIONS SONT LIMITÉES EN NOMBRE; ET LES HISTOIRES PEUVENT ÊTRE MODIFIÉES OU RETIRÉES DU CATALOGUE.</p>

    <p>LA SOCIÉTÉ NE GARANTIT PAS QU’ELLE METTRA À JOUR LES SERVICES NI QU’ELLE CONTINUERA DE LES OFFRIR OU DE LES RENDRE DISPONIBLES, Y COMPRIS SANS LIMITATION TOUTE HISTOIRE, FONCTIONNALITÉ OU PALIER DE QUALITÉ, PENDANT UNE PÉRIODE DONNÉE. CERTAINES JURIDICTIONS N’AUTORISENT PAS L’EXCLUSION DE CERTAINES GARANTIES; CERTAINES DES EXCLUSIONS CI-DESSUS POURRAIENT DONC NE PAS S’APPLIQUER À VOUS.</p>

    <ol className="heading" start={8}><li><strong>CONTENU DE TIERS.</strong></li></ol>

    <p>Les Services peuvent contenir des liens vers du matériel de tiers qui n’appartient pas à la Société et qu’elle ne contrôle pas, y compris l’App Store, Google Play et les sites Web de nos fournisseurs. La Société n’endosse pas ces sites, renseignements, matériels, produits ou services de tiers et n’en assume aucune responsabilité. Votre utilisation de ceux-ci est régie par leurs propres conditions et politiques.</p>

    <ol className="heading" start={9}><li><strong>INDEMNISATION.</strong></li></ol>

    <p>Dans toute la mesure permise par la loi, vous acceptez d’indemniser, de défendre et de dégager de toute responsabilité la Société ainsi que ses dirigeants, administrateurs, employés, entrepreneurs, mandataires, concédants de licence et fournisseurs à l’égard de toute réclamation, responsabilité, dommage, jugement, sentence, perte, coût, dépense ou honoraires (y compris les honoraires d’avocat raisonnables) découlant de votre violation des présentes Conditions, de votre Contenu d’utilisateur ou de votre utilisation des Services, ou s’y rapportant.</p>

    <ol className="heading" start={10}><li><strong>LIMITATION DE RESPONSABILITÉ.</strong></li></ol>

    <p>DANS TOUTE LA MESURE PERMISE PAR LA LOI APPLICABLE, EN AUCUN CAS LA SOCIÉTÉ, SES SOCIÉTÉS AFFILIÉES OU LEURS CONCÉDANTS DE LICENCE, FOURNISSEURS DE SERVICES, EMPLOYÉS, MANDATAIRES, DIRIGEANTS OU ADMINISTRATEURS NE SERONT RESPONSABLES DE DOMMAGES DE QUELQUE NATURE QUE CE SOIT, EN VERTU DE QUELQUE THÉORIE JURIDIQUE QUE CE SOIT, DÉCOULANT DE VOTRE UTILISATION DES SERVICES OU DE VOTRE INCAPACITÉ À LES UTILISER, OU S’Y RAPPORTANT, Y COMPRIS LES DOMMAGES DIRECTS, INDIRECTS, SPÉCIAUX, ACCESSOIRES, CONSÉCUTIFS OU PUNITIFS, Y COMPRIS SANS LIMITATION LES BLESSURES CORPORELLES, LA DOULEUR ET LES SOUFFRANCES, LA DÉTRESSE ÉMOTIONNELLE, LA PERTE DE REVENUS, LA PERTE DE PROFITS, LA PERTE D’AFFAIRES OU D’ÉCONOMIES PRÉVUES, LA PERTE D’USAGE, LA PERTE D’ACHALANDAGE, LA PERTE DE DONNÉES (Y COMPRIS LES HISTOIRES SAUVEGARDÉES ET LES CRÉDITS), QU’ILS SOIENT CAUSÉS PAR UN DÉLIT (Y COMPRIS LA NÉGLIGENCE), UNE VIOLATION DE CONTRAT OU AUTREMENT, MÊME S’ILS ÉTAIENT PRÉVISIBLES.</p>

    <p>EN AUCUN CAS LA RESPONSABILITÉ GLOBALE DE LA SOCIÉTÉ DÉCOULANT DES PRÉSENTES CONDITIONS OU DES SERVICES, OU S’Y RAPPORTANT, NE DÉPASSERA LE PLUS ÉLEVÉ DES MONTANTS SUIVANTS : (A) LES SOMMES QUE VOUS AVEZ VERSÉES À LA SOCIÉTÉ POUR LES SERVICES AU COURS DES DOUZE (12) MOIS PRÉCÉDANT L’ÉVÉNEMENT À L’ORIGINE DE LA RÉCLAMATION, OU (B) CENT DOLLARS AMÉRICAINS (100 $ US). CE QUI PRÉCÈDE N’A AUCUNE INCIDENCE SUR TOUTE RESPONSABILITÉ QUI NE PEUT ÊTRE EXCLUE OU LIMITÉE EN VERTU DE LA LOI APPLICABLE.</p>

    <ol className="heading" start={11}><li><strong>DURÉE ET RÉSILIATION.</strong></li></ol>

    <p>Les présentes Conditions demeurent en vigueur jusqu’à leur résiliation. Vous pouvez les résilier à tout moment en supprimant votre Compte d’utilisateur dans l’Application (Profil &gt; Réglages &gt; Supprimer le compte) et en cessant toute utilisation des Services. Nous pouvons suspendre ou résilier votre accès aux Services, avec ou sans préavis, pour quelque raison que ce soit, notamment si nous croyons raisonnablement que vous avez enfreint les présentes Conditions. À la résiliation, votre licence d’utilisation des Services prend fin, tout Crédit restant est perdu, et les articles 3(d) à (f), 4, 6(d), 7, 9, 10, 11, 12, 13 et 14 survivent.</p>

    <ol className="heading" start={12}><li><strong>DROIT APPLICABLE.</strong></li></ol>

    <p>Les présentes Conditions et tout différend en découlant ou s’y rapportant, ou se rapportant aux Services, sont régis par les lois de l’État du Delaware et interprétés conformément à celles-ci, sans égard à ses règles de conflit de lois, et, le cas échéant, par la Federal Arbitration Act. Sous réserve de l’article 13, tout différend non soumis à l’arbitrage sera porté exclusivement devant les tribunaux étatiques ou fédéraux situés au Delaware, et vous consentez à la compétence personnelle de ces tribunaux.</p>

    <p><strong>Résidents du Canada.</strong> Si vous résidez au Canada, les présentes Conditions et tout différend en découlant ou s’y rapportant, ou se rapportant aux Services, sont régis par les lois de la province de l’Ontario et les lois fédérales du Canada qui s’y appliquent, sans égard aux règles de conflit de lois. Sous réserve de l’article 13, et dans la mesure où un différend n’est pas soumis à l’arbitrage, vous acceptez la compétence exclusive des tribunaux situés à Toronto, en Ontario. Rien dans les présentes Conditions ne limite les droits que vous confère la législation impérative de protection du consommateur de votre province, y compris le droit d’intenter une action devant votre tribunal local lorsque cette législation le prévoit.</p>

    <ol className="heading" start={13} id="disputes"><li><strong>RÈGLEMENT DES DIFFÉRENDS; CONVENTION D’ARBITRAGE; RENONCIATION AUX RECOURS COLLECTIFS ET AU PROCÈS DEVANT JURY.</strong></li></ol>

    <p><strong>VEUILLEZ LIRE ATTENTIVEMENT LA PRÉSENTE SECTION. ELLE A UNE INCIDENCE SUR VOS DROITS.</strong></p>

    <p><strong>a. Règlement informel.</strong> Avant d’intenter une réclamation contre la Société, vous acceptez de tenter de régler le différend de façon informelle en envoyant un avis écrit décrivant le différend et la réparation demandée à <a href="mailto:hi@cielpm.ai">hi@cielpm.ai</a>. Nous tenterons de même de régler tout différend avec vous de façon informelle en communiquant avec vous à l’adresse courriel associée à votre Compte d’utilisateur. Si un différend n’est pas réglé dans les 60 jours suivant l’envoi de l’avis, l’une ou l’autre des parties peut engager l’arbitrage décrit ci-dessous.</p>

    <p><strong>b. Arbitrage exécutoire.</strong> À l’exception (i) des réclamations admissibles devant la cour des petites créances et (ii) des demandes d’injonction relatives à la propriété intellectuelle, vous et la Société convenez que tout différend, réclamation ou controverse découlant des présentes Conditions ou des Services, ou s’y rapportant, sera réglé exclusivement par arbitrage définitif et exécutoire administré par l’American Arbitration Association (« AAA ») en vertu de ses Consumer Arbitration Rules. L’arbitrage sera mené par un seul arbitre, en anglais, et pourra se tenir par visioconférence ou dans le comté où vous résidez. La sentence arbitrale pourra être homologuée par tout tribunal compétent. La Société paiera l’ensemble des frais de dépôt, d’administration et d’arbitre de l’AAA pour les réclamations inférieures à 10 000 $ US, à moins que l’arbitre ne juge la réclamation frivole.</p>

    <p><strong>Résidents du Canada.</strong> Si vous résidez au Canada, le paragraphe précédent s’applique, sauf que (i) les réclamations que la législation impérative de protection du consommateur de votre province vous permet d’intenter devant un tribunal malgré une convention d’arbitrage sont également exclues, et (ii) tout différend sera plutôt administré par l’Institut d’arbitrage et de médiation du Canada (ADRIC) en vertu de ses Règles d’arbitrage, par un seul arbitre, en français ou en anglais à votre choix, par visioconférence ou dans la ville où vous résidez, la Société payant les frais de dépôt, d’administration et d’arbitre pour les réclamations inférieures à 10 000 $ CA, à moins que l’arbitre ne juge la réclamation frivole.</p>

    <p><strong>c. Renonciation aux recours collectifs.</strong> VOUS ET LA SOCIÉTÉ CONVENEZ QUE CHACUN NE PEUT INTENTER DE RÉCLAMATION CONTRE L’AUTRE QU’À TITRE INDIVIDUEL, ET NON À TITRE DE DEMANDEUR OU DE MEMBRE D’UN GROUPE DANS LE CADRE D’UN RECOURS COLLECTIF OU D’UNE PROCÉDURE REPRÉSENTATIVE. L’arbitre ne peut réunir les réclamations de plus d’une personne ni présider une procédure collective ou représentative de quelque forme que ce soit. Si la présente renonciation est jugée inapplicable à une réclamation donnée, cette réclamation sera dissociée et portée devant les tribunaux, et le reste de la présente section continuera de s’appliquer.</p>

    <p><strong>d. Renonciation au procès devant jury.</strong> DANS LA MESURE PERMISE PAR LA LOI, VOUS ET LA SOCIÉTÉ RENONCEZ À TOUT DROIT À UN PROCÈS DEVANT JURY pour toute réclamation portée devant les tribunaux plutôt qu’en arbitrage.</p>

    <p><strong>e. Retrait.</strong> Vous pouvez vous retirer de la présente convention d’arbitrage en écrivant à <a href="mailto:hi@cielpm.ai">hi@cielpm.ai</a>, avec la mention « Retrait de l’arbitrage » en objet et l’adresse courriel de votre Compte d’utilisateur, dans les 30 jours suivant votre première acceptation des présentes Conditions. Ce retrait n’a aucune incidence sur les autres dispositions des présentes Conditions.</p>

    <p><strong>f. Modifications.</strong> Si nous modifions la présente section après votre acceptation des Conditions, vous pouvez rejeter la modification en nous écrivant dans les 30 jours suivant celle-ci, auquel cas la version de la présente section que vous avez acceptée en dernier continuera de s’appliquer aux différends entre nous.</p>

    <ol className="heading" start={14}><li><strong>DISPOSITIONS GÉNÉRALES.</strong></li></ol>

    <p><strong>a. Conditions de l’App Store.</strong> Si vous avez téléchargé l’Application sur l’App Store d’Apple, ce qui suit s’applique : les présentes Conditions sont conclues entre vous et la Société uniquement, et non avec Apple Inc. (« Apple »). Apple n’est pas responsable de l’Application ni de son contenu. La licence qui vous est accordée se limite à une licence non transférable d’utilisation de l’Application sur des produits de marque Apple que vous possédez ou contrôlez, conformément aux règles d’utilisation énoncées dans les Conditions générales des services multimédias d’Apple. Apple n’a aucune obligation de fournir des services de maintenance ou d’assistance pour l’Application. En cas de non-conformité de l’Application à une garantie applicable, vous pouvez en aviser Apple, qui vous remboursera le prix d’achat de l’Application (le cas échéant); dans toute la mesure permise par la loi, Apple n’a aucune autre obligation de garantie à l’égard de l’Application. Apple n’est pas responsable du traitement des réclamations de votre part ou de la part de tiers relatives à l’Application ou à votre possession ou utilisation de celle-ci, y compris les réclamations en responsabilité du fait des produits, les réclamations selon lesquelles l’Application ne respecte pas une exigence légale ou réglementaire applicable, et les réclamations fondées sur la protection du consommateur ou une législation semblable. En cas de réclamation d’un tiers selon laquelle l’Application porte atteinte à ses droits de propriété intellectuelle, c’est la Société, et non Apple, qui est responsable de l’enquête, de la défense, du règlement et de la libération de cette réclamation. Vous déclarez ne pas vous trouver dans un pays visé par un embargo du gouvernement américain ou désigné par celui-ci comme « soutenant le terrorisme », et ne figurer sur aucune liste du gouvernement américain de parties interdites ou restreintes. Apple et ses filiales sont des tiers bénéficiaires des présentes Conditions et peuvent les faire valoir contre vous.</p>

    <p><strong>b. Intégralité de l’entente.</strong> Les présentes Conditions, ainsi que la Politique de confidentialité et toute Condition supplémentaire, constituent l’intégralité de l’entente entre vous et la Société concernant les Services et remplacent toute entente antérieure.</p>

    <p><strong>c. Divisibilité; renonciation.</strong> Si une disposition des présentes Conditions est jugée invalide ou inapplicable, elle sera appliquée dans toute la mesure permise et les autres dispositions demeureront pleinement en vigueur. Notre omission de faire valoir un droit ou une disposition ne constitue pas une renonciation à ce droit ou à cette disposition.</p>

    <p><strong>d. Cession.</strong> Vous ne pouvez céder ni transférer les présentes Conditions ou votre Compte d’utilisateur sans notre consentement écrit préalable. Nous pouvons céder les présentes Conditions sans restriction, y compris dans le cadre d’une fusion, d’une acquisition ou d’une vente d’actifs.</p>

    <p><strong>e. Exportation.</strong> Vous acceptez de vous conformer à toutes les lois et à tous les règlements applicables en matière de contrôle des exportations et des réexportations dans le cadre de votre utilisation des Services.</p>

    <p><strong>f. Avis.</strong> Nous pouvons vous transmettre des avis par courriel, par affichage dans l’Application ou sur le Site Web, ou par tout autre moyen raisonnable. Les avis destinés à la Société doivent être envoyés à <a href="mailto:hi@cielpm.ai">hi@cielpm.ai</a>.</p>

    <p><strong>g. Langue.</strong> Les parties ont demandé que les présentes Conditions et tous les documents connexes soient rédigés en français. Une <Link to="/terms">version anglaise</Link> est également offerte. En cas de divergence, la version française prévaut pour les résidents du Québec; ailleurs, la version anglaise prévaut.</p>

    <ol className="heading" start={15}><li><strong>NOUS JOINDRE.</strong></li></ol>

    <p>Pour toute question sur les présentes Conditions ou sur les Services, écrivez-nous à <a href="mailto:hi@cielpm.ai">hi@cielpm.ai</a>.</p>
    </>
  );
}
